name: 'GitHub Actions Weather Bot'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail 1st'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Schedule Weather Report (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: "xuhan@smail.nju.edu.cn,xu.han@smail.nju.edu.cn"
          from: GitHub Actions
      - name: 'Send mail 2nd'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME_2 }}
          password: ${{ secrets.MAIL_PASSWORD_2 }}
          subject: Schedule Weather Report (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: 914966103@qq.com
          from: GitHub Actions
      - name: 'Send mail 3rd'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME_3 }}
          password: ${{ secrets.MAIL_PASSWORD_3 }}
          subject: Schedule Weather Report (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: 914966103@qq.com
          from: GitHub Actions
